# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-09-24T10:28:41+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, RootModel, conint


class TaskState(Enum):
    staged = 'staged'
    running = 'running'
    succeeded = 'succeeded'
    failed = 'failed'
    skipped = 'skipped'


class QueueState(Enum):
    unsubmitted = 'unsubmitted'
    submitted = 'submitted'
    executing = 'executing'
    completed = 'completed'


class QueueFinishReason(Enum):
    success = 'success'
    abort_on_failure = 'abort_on_failure'
    finished_with_failures = 'finished_with_failures'
    manually_stopped = 'manually_stopped'


class CandidateOrigin(Enum):
    imported = 'imported'
    returned_unrun = 'returned_unrun'
    returned_failed = 'returned_failed'
    returned_succeeded = 'returned_succeeded'


class FailureCause(Enum):
    manually_stopped = 'manually_stopped'
    program_error = 'program_error'
    external_interrupt = 'external_interrupt'
    predecessor_failed = 'predecessor_failed'
    queue_manually_stopped = 'queue_manually_stopped'


class SeatKind(Enum):
    task = 'task'
    queue = 'queue'


class EffectKind(Enum):
    immediate = 'immediate'
    immediate_retroactive = 'immediate_retroactive'
    new_submissions = 'new_submissions'
    on_restart = 'on_restart'


class Error(BaseModel):
    code: str = Field(
        ...,
        description='SCREAMING_SNAKE_CASE 错误码全集枚举（见文件头/m0-plan §2.1.1）',
    )
    message: str
    details: dict[str, Any] | None = Field(
        None, description='错误附加信息（如越界值、逐字段错误数组）'
    )


class ErrorBody(BaseModel):
    error: Error


class PageEnvelope(BaseModel):
    items: list[dict[str, Any]] = Field(
        ..., description='当前页数据（具体 schema 由各端点 response 覆盖）'
    )
    page: conint(ge=1)
    page_size: conint(ge=1, le=200)
    total: conint(ge=0)


class Candidate(BaseModel):
    id: int = Field(
        ..., description='C；与后续 Task 同 id（跨形态延续，roadmap §2.6 ③）'
    )
    filename: str = Field(..., description='C；导入文件名（退回候选沿用任务文件名）')
    origin: CandidateOrigin
    failure_note: str = Field(
        ..., description='C；仅 returned_failed：归因附注；其余 null'
    )
    created_at: AwareDatetime = Field(..., description='C；补充字段提案')
    title: str | None = Field(
        None,
        description='—；响应中实时解析注入（解析失败为 null），不落库（roadmap §2.6 ①）',
    )


class Task(BaseModel):
    id: int = Field(..., description='C；同候选 id')
    queue_id: str | None = Field(None, description='C/T；归属队列，直接提交者为 null')
    position: conint(ge=0) = Field(..., description='T；队列内顺序（0 起）')
    time_limit_s: int = Field(
        ..., description='C/T；墙钟上限，0=不限制；M0/M1 契约占位'
    )
    state: TaskState = Field(..., description='T；派生展示字段')


class Member(BaseModel):
    task_id: int | None = None
    state: TaskState | None = None
    cause: FailureCause | None = None


class LastFailure(BaseModel):
    finish_reason: QueueFinishReason | None = None
    failure_positions: list[int] | None = Field(None, description='失败位置（任务 id）')
    members: list[Member] | None = None


class FinishReasonEnum(Enum):
    success = 'success'
    abort_on_failure = 'abort_on_failure'
    finished_with_failures = 'finished_with_failures'
    manually_stopped = 'manually_stopped'


class FinishReason(RootModel[FinishReasonEnum | None]):
    root: FinishReasonEnum | None = Field(
        None, description='T；最近一次执行结束时写入；取值同 QueueFinishReason'
    )


class Queue(BaseModel):
    id: str = Field(..., description='C；随机 6 位 base32（生成时对照全库查重）')
    name: str = Field(..., description='C/T；默认 yyyymmddhhmmss 时间戳')
    member_ids: list[int] = Field(
        ..., description='C/T；有序成员（创建校验 2–10；此后只减不增、≥1)'
    )
    skip_failed: bool = Field(..., description='C/T；跳过失败任务开关')
    state: QueueState
    rollback_flag: bool = Field(..., description='T；失败回退标记')
    rollback_count: conint(ge=0) = Field(..., description='T；回退次数，0 起')
    last_failure: LastFailure = Field(..., description='T；队列成功终态时清 null')
    finish_reason: FinishReason = Field(
        ..., description='T；最近一次执行结束时写入；取值同 QueueFinishReason'
    )
    created_at: AwareDatetime = Field(..., description='C；补充字段提案')
    updated_at: AwareDatetime | None = Field(None, description='T；补充字段提案')


class Member1(BaseModel):
    task_id: int
    filename: str
    state: TaskState


class PendingSeat(BaseModel):
    seat_id: int = Field(..., description='C；席位标识（追加自增）')
    kind: SeatKind
    task_id: int | None = Field(None, description='C；kind=task 时')
    queue_id: str | None = Field(None, description='C；kind=queue 时')
    position: conint(ge=0) = Field(..., description='T；席位顺序（0 起）')
    members: list[Member1] = Field(
        ..., description='T；队列席位成员概览（kind=task 为单元素）'
    )
    locked: bool = Field(..., description='T；并行窗口已触及 → 不可整席重排/移除')


class Capacity(BaseModel):
    limit: int = Field(..., description='在途席位上限（运行级设置，默认 3）')
    occupied: int
    available: int


class PendingResponse(BaseModel):
    seats: list[PendingSeat]
    capacity: Capacity
    window_size: int = Field(..., description='当前并行执行数')


class Nproc(BaseModel):
    value: int
    defaulted: bool


class MemGb(BaseModel):
    value: float
    defaulted: bool


class Resources(BaseModel):
    nproc: Nproc
    mem_gb: MemGb


class Monitor(BaseModel):
    cpu_percent: float | None = None
    mem_rss_mb: float | None = None
    elapsed_s: float | None = None


class Progress(BaseModel):
    opt_step: int | None = None
    scf_cycle: int | None = None
    converged: bool | None = None
    last_line: str | None = None


class Execution(BaseModel):
    id: int = Field(..., description='C；派发时创建；run/<id>/ 派生')
    task_id: int = Field(..., description='C')
    queue_id: str = Field(..., description='C')
    state: TaskState = Field(
        ..., description='运行视图只出现 running（staged 由 /pending 表达）'
    )
    filename: str = Field(..., description='C；冗余自任务，列表展示用')
    submitted_at: AwareDatetime = Field(..., description='C')
    started_at: AwareDatetime | None = Field(None, description='T；running 时补')
    input_hash: str = Field(..., description='C；sha256:<hex>，skipped 无（null）')
    resources: Resources = Field(
        ..., description='C；Link0 声明与补齐标记（roadmap §2.6）'
    )
    hq_job_id: int | None = Field(
        None, description='T；提交 HQ 后回填（M0 mock 给演示值）'
    )
    monitor: Monitor | None = Field(None, description='T；运行中实时（psutil）')
    progress: Progress | None = Field(None, description='T；增量解析注入')


class CauseEnum(Enum):
    manually_stopped = 'manually_stopped'
    program_error = 'program_error'
    external_interrupt = 'external_interrupt'
    predecessor_failed = 'predecessor_failed'
    queue_manually_stopped = 'queue_manually_stopped'


class Cause(RootModel[CauseEnum | None]):
    root: CauseEnum | None = Field(
        None, description='F；终态归因（同 FailureCause）；succeeded 为 null'
    )


class MonitorSummary(BaseModel):
    cpu_peak_percent: float | None = None
    mem_peak_mb: float | None = None
    stall_alerts: int | None = None
    stall_total_minutes: float | None = None


class ChkSnapshot(BaseModel):
    protected: bool
    location: str = Field(..., description='保护子目录位置；正常结束时 null')


class HistoryEntry(Execution):
    finished_at: AwareDatetime = Field(..., description='F')
    cause: Cause = Field(
        ..., description='F；终态归因（同 FailureCause）；succeeded 为 null'
    )
    wall_time_s: float = Field(..., description='F；started_at→finished_at 派生')
    monitor_summary: MonitorSummary | None = Field(None, description='F；仅 succeeded')
    chk_snapshot: ChkSnapshot = Field(
        ..., description='F；非正常终止保全快照标记与位置'
    )
    archived: bool = Field(..., description='F→；冻结后唯一可变字段')
    result_ref: str = Field(
        ..., description='M3 占位，恒 null（Result 字段全集随 M3 契约 diff 一次性扩展）'
    )


class MoleculeSummary(BaseModel):
    atom_count: int
    formula: str = Field(..., description='Hill 记法，如 H2O1、C6H6O1（计数 1 显式）')
    variables_present: bool
    constants_present: bool


class InputBlock(BaseModel):
    lines: list[str]
    terminator_blank: bool = Field(
        ..., description='该节是否需要终止空行（以手册 Section Ordering 表逐节为准）'
    )


class Link0(BaseModel):
    lines: list[str]
    missing: list[str] = Field(
        ..., description='缺失 %NProcShared/%Mem 等（驱动提交确认框琥珀警告）'
    )


class Blocks(BaseModel):
    link0: Link0
    route: str
    title: str
    charge_mult: str
    molecule: MoleculeSummary
    additional_sections: list[InputBlock]


class ParseError(BaseModel):
    section: str
    line: int
    message: str


class InputPreview(BaseModel):
    candidate_id: int
    filename: str
    blocks: Blocks
    parse_errors: list[ParseError] | None = Field(
        None, description='解析失败节信息（预览尽力而为；导入端点才严格校验）'
    )


class ValueType(Enum):
    string = 'string'
    integer = 'integer'
    number = 'number'
    boolean = 'boolean'


class Range(BaseModel):
    min: float | None = None
    max: float | None = None


class SettingItem(BaseModel):
    key: str
    value: str | int | float | bool = Field(
        ..., description='实际值（scalar；类型由 value_type 决定）'
    )
    value_type: ValueType | None = None
    range: Range | None = None
    editable: bool = Field(..., description='false=启动级只读')
    effect: EffectKind
    env_var: str | None = Field(
        None, description='启动级参数的环境变量名（G16WEB_ 前缀）'
    )
    description: str | None = None


class SettingsResponse(BaseModel):
    startup: list[SettingItem]
    runtime: list[SettingItem]


class SettingsUpdate(BaseModel):
    values: dict[str, Any]


class File(BaseModel):
    id: int | None = None
    filename: str | None = None


class CandidateCreate(BaseModel):
    files: list[File]


class SubmitResponse(BaseModel):
    seat_id: int
    task_id: int
