# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-09-28T18:39:47+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, RootModel, conint


class TaskState(Enum):
    staged = 'staged'
    running = 'running'
    succeeded = 'succeeded'
    failed = 'failed'
    skipped = 'skipped'


class QueueState(Enum):
    unsubmitted = 'unsubmitted'
    submitted = 'submitted'
    executing = 'executing'
    completed = 'completed'


class QueueFinishReason(Enum):
    success = 'success'
    abort_on_failure = 'abort_on_failure'
    finished_with_failures = 'finished_with_failures'
    manually_stopped = 'manually_stopped'


class CandidateOrigin(Enum):
    imported = 'imported'
    returned_unrun = 'returned_unrun'
    returned_failed = 'returned_failed'
    returned_succeeded = 'returned_succeeded'


class HistorySort(Enum):
    submitted_desc = 'submitted_desc'
    finished_desc = 'finished_desc'
    finished_asc = 'finished_asc'
    filename_asc = 'filename_asc'
    filename_desc = 'filename_desc'


class QueueSortKey(Enum):
    default = 'default'
    name_asc = 'name_asc'
    name_desc = 'name_desc'


class UiPreferences(BaseModel):
    prefs: dict[str, str] = Field(
        ..., description='偏好键值（仅含已持久化键；值为所选排序枚举串）'
    )


class UiPreferencesUpdate(BaseModel):
    prefs: dict[str, str] = Field(
        ...,
        description='键白名单与值域：queues.sort ∈ QueueSortKey；history.sort 与 archive.sort ∈ HistorySort（归档页与历史页同组件、键分立各自记忆）。 未知键或越域值整批 400 INVALID_REQUEST。',
    )


class FailureCause(Enum):
    manually_stopped = 'manually_stopped'
    program_error = 'program_error'
    external_interrupt = 'external_interrupt'
    predecessor_failed = 'predecessor_failed'
    queue_manually_stopped = 'queue_manually_stopped'


class SeatKind(Enum):
    task = 'task'
    queue = 'queue'


class EffectKind(Enum):
    immediate = 'immediate'
    immediate_retroactive = 'immediate_retroactive'
    new_submissions = 'new_submissions'
    on_restart = 'on_restart'


class Error(BaseModel):
    code: str = Field(
        ...,
        description='SCREAMING_SNAKE_CASE 错误码全集枚举（SSOT 载体见本文件头「错误码全集」清单，24 码 + 两张 reason 词表）',
    )
    message: str
    details: dict[str, Any] | None = Field(
        None, description='错误附加信息（如越界值、逐字段错误数组）'
    )


class ErrorBody(BaseModel):
    error: Error


class PageEnvelope(BaseModel):
    items: list[dict[str, Any]] = Field(
        ..., description='当前页数据（具体 schema 由各端点 response 覆盖）'
    )
    page: conint(ge=1)
    page_size: conint(ge=1, le=200)
    total: conint(ge=0)


class Candidate(BaseModel):
    id: int = Field(
        ..., description='C；与后续 Task 同 id（跨形态延续，roadmap §2.6 ③）'
    )
    filename: str = Field(..., description='C；导入文件名（退回候选沿用任务文件名）')
    origin: CandidateOrigin
    failure_note: str = Field(
        ..., description='C；仅 returned_failed：归因附注；其余 null'
    )
    created_at: AwareDatetime = Field(..., description='C；补充字段提案')
    title: str | None = Field(
        None,
        description='—；响应中实时解析注入（解析失败为 null），不落库（roadmap §2.6 ①）',
    )


class Task(BaseModel):
    id: int = Field(..., description='C；同候选 id')
    queue_id: str | None = Field(None, description='C/T；归属队列，直接提交者为 null')
    position: conint(ge=0) = Field(..., description='T；队列内顺序（0 起）')
    time_limit_s: int = Field(
        ..., description='C/T；墙钟上限，0=不限制；M0/M1 契约占位'
    )
    state: TaskState = Field(..., description='T；派生展示字段')


class Member(BaseModel):
    task_id: int | None = None
    state: TaskState | None = None
    cause: FailureCause | None = None


class LastFailure(BaseModel):
    finish_reason: QueueFinishReason | None = None
    failure_positions: list[int] | None = Field(None, description='失败位置（任务 id）')
    members: list[Member] | None = None


class FinishReasonEnum(Enum):
    success = 'success'
    abort_on_failure = 'abort_on_failure'
    finished_with_failures = 'finished_with_failures'
    manually_stopped = 'manually_stopped'


class FinishReason(RootModel[FinishReasonEnum | None]):
    root: FinishReasonEnum | None = Field(
        None, description='T；最近一次执行结束时写入；取值同 QueueFinishReason'
    )


class Queue(BaseModel):
    id: str = Field(..., description='C；随机 6 位 base32（生成时对照全库查重）')
    name: str = Field(..., description='C/T；默认 yyyymmddhhmmss 时间戳')
    member_ids: list[int] = Field(
        ..., description='C/T；有序成员（创建校验 2–10；此后只减不增、≥1)'
    )
    skip_failed: bool = Field(..., description='C/T；跳过失败任务开关')
    state: QueueState
    rollback_flag: bool = Field(..., description='T；失败回退标记')
    rollback_count: conint(ge=0) = Field(..., description='T；回退次数，0 起')
    last_failure: LastFailure = Field(..., description='T；队列成功终态时清 null')
    finish_reason: FinishReason = Field(
        ..., description='T；最近一次执行结束时写入；取值同 QueueFinishReason'
    )
    created_at: AwareDatetime = Field(..., description='C；补充字段提案')
    updated_at: AwareDatetime | None = Field(None, description='T；补充字段提案')


class Nproc(BaseModel):
    value: int
    defaulted: bool


class MemGb(BaseModel):
    value: float
    defaulted: bool


class Resources(BaseModel):
    nproc: Nproc
    mem_gb: MemGb


class Member1(BaseModel):
    task_id: int
    filename: str
    state: TaskState
    position: conint(ge=0) | None = Field(
        None, description='T；队列内序号（0 起）；kind=task 席位为 null'
    )
    title: str | None = Field(
        None,
        description='—；响应中实时解析注入（解析失败为 null），不落库（同候选 title 口径）',
    )
    resources: Resources | None = None


class PendingSeat(BaseModel):
    seat_id: int = Field(..., description='C；席位标识（追加自增）')
    kind: SeatKind
    task_id: int | None = Field(None, description='C；kind=task 时')
    queue_id: str | None = Field(None, description='C；kind=queue 时')
    queue_name: str | None = Field(
        None, description='C；kind=queue 时的队列名（实时取自队列）'
    )
    submitted_at: AwareDatetime = Field(
        ..., description='T；入席时刻即提交时刻（席位 created_at）'
    )
    position: conint(ge=0) = Field(..., description='T；席位顺序（0 起）')
    members: list[Member1] = Field(
        ...,
        description='T；队列席位成员概览（kind=task 为单元素）；title/resources 实时解析，输入文件不可读时 resources 键缺省',
    )
    locked: bool = Field(..., description='T；并行窗口已触及 → 不可整席重排/移除')


class Capacity(BaseModel):
    limit: int = Field(..., description='在途席位上限（运行级设置，默认 3）')
    occupied: int
    available: int


class PendingResponse(BaseModel):
    seats: list[PendingSeat]
    capacity: Capacity
    window_size: int = Field(..., description='当前并行执行数')


class Monitor(BaseModel):
    cpu_percent: float | None = None
    mem_rss_mb: float | None = None
    elapsed_s: float | None = None


class Progress(BaseModel):
    opt_step: int | None = None
    scf_cycle: int | None = None
    converged: bool | None = None
    last_line: str | None = None


class Execution(BaseModel):
    id: int = Field(..., description='C；派发时创建；run/<id>/ 派生')
    task_id: int = Field(..., description='C')
    queue_id: str = Field(..., description='C')
    state: TaskState = Field(
        ..., description='运行视图只出现 running（staged 由 /pending 表达）'
    )
    filename: str = Field(..., description='C；冗余自任务，列表展示用')
    submitted_at: AwareDatetime = Field(..., description='C')
    started_at: AwareDatetime | None = Field(None, description='T；running 时补')
    input_hash: str = Field(..., description='C；sha256:<hex>，skipped 无（null）')
    resources: Resources
    hq_job_id: int | None = Field(
        None, description='T；提交 HQ 后回填（M0 mock 给演示值）'
    )
    monitor: Monitor | None = Field(None, description='T；运行中实时（psutil）')
    progress: Progress | None = Field(None, description='T；增量解析注入')


class CauseEnum(Enum):
    manually_stopped = 'manually_stopped'
    program_error = 'program_error'
    external_interrupt = 'external_interrupt'
    predecessor_failed = 'predecessor_failed'
    queue_manually_stopped = 'queue_manually_stopped'


class Cause(RootModel[CauseEnum | None]):
    root: CauseEnum | None = Field(
        None, description='F；终态归因（同 FailureCause）；succeeded 为 null'
    )


class MonitorSummary(BaseModel):
    cpu_peak_percent: float | None = None
    mem_peak_mb: float | None = None
    stall_alerts: int | None = None
    stall_total_minutes: float | None = None


class ChkSnapshot(BaseModel):
    protected: bool
    location: str = Field(..., description='保护子目录位置；正常结束时 null')


class HistoryEntry(Execution):
    finished_at: AwareDatetime = Field(..., description='F')
    cause: Cause = Field(
        ..., description='F；终态归因（同 FailureCause）；succeeded 为 null'
    )
    wall_time_s: float = Field(..., description='F；started_at→finished_at 派生')
    monitor_summary: MonitorSummary | None = Field(None, description='F；仅 succeeded')
    chk_snapshot: ChkSnapshot = Field(
        ..., description='F；非正常终止保全快照标记与位置'
    )
    archived: bool = Field(..., description='F→；冻结后唯一可变字段')
    result_ref: str = Field(
        ..., description='M3 占位，恒 null（Result 字段全集随 M3 契约 diff 一次性扩展）'
    )


class MoleculeSummary(BaseModel):
    atom_count: int
    formula: str = Field(..., description='Hill 记法，如 H2O1、C6H6O1（计数 1 显式）')
    variables_present: bool
    constants_present: bool


class InputBlock(BaseModel):
    lines: list[str]
    terminator_blank: bool = Field(
        ..., description='该节是否需要终止空行（以手册 Section Ordering 表逐节为准）'
    )


class Link0(BaseModel):
    lines: list[str]
    missing: list[str] = Field(
        ..., description='缺失 %NProcShared/%Mem 等（驱动提交确认框琥珀警告）'
    )


class Blocks(BaseModel):
    link0: Link0
    route: str
    title: str
    charge_mult: str
    molecule: MoleculeSummary
    additional_sections: list[InputBlock]


class ParseError(BaseModel):
    section: str
    line: int
    message: str


class InputPreview(BaseModel):
    candidate_id: int
    filename: str
    blocks: Blocks
    parse_errors: list[ParseError] | None = Field(
        None, description='解析失败节信息（预览尽力而为；导入端点才严格校验）'
    )


class ValueType(Enum):
    string = 'string'
    integer = 'integer'
    number = 'number'
    boolean = 'boolean'


class Range(BaseModel):
    min: float | None = None
    max: float | None = None
    enum: list[str] | None = Field(
        None,
        description='枚举值域（string 型参数载体，如 update_check_interval 的 daily/weekly/monthly/never 四档）；非枚举参数缺省。校验不命中归 type 类错误（不扩 reason 词表）',
    )


class SettingItem(BaseModel):
    key: str
    value: str | int | float | bool = Field(
        ..., description='实际值（scalar；类型由 value_type 决定）'
    )
    value_type: ValueType | None = None
    range: Range | None = None
    editable: bool = Field(..., description='false=启动级只读')
    effect: EffectKind
    env_var: str | None = Field(
        None, description='启动级参数的环境变量名（G16WEB_ 前缀）'
    )
    description: str | None = None


class SettingsResponse(BaseModel):
    startup: list[SettingItem]
    runtime: list[SettingItem]


class SettingsUpdate(BaseModel):
    values: dict[str, Any]


class UpdatePhase(Enum):
    idle = 'idle'
    checking = 'checking'
    available = 'available'
    up_to_date = 'up_to_date'
    downloading = 'downloading'
    installing = 'installing'
    restarting = 'restarting'
    done = 'done'
    failed = 'failed'


class UpdateStatus(BaseModel):
    current_version: str = Field(
        ...,
        description='当前版本（带 v 前缀形态，如 v2.1.0；与 /system/health version 同源）',
    )
    latest_version: str | None = Field(
        None,
        description='最近一次检查发现的远端版本（带 v 前缀）；从未检查成功过为 null',
    )
    last_checked_at: AwareDatetime | None = Field(
        None,
        description='最近一次检查结束时刻（含失败；跨服务重启经部署目录 .update-check 恢复）',
    )
    phase: UpdatePhase
    message: str | None = Field(
        None,
        description='供前端逐字展示的当前状态/异常文案（§3.2/§3.5 文案表，全角标点）',
    )
    proxy: str = Field(
        ...,
        description='代理通道（读自工作区 .update-proxy，与 update.sh 共用配置；null=直连；默认代理为 URL 串 https://v4.gh-proxy.org）',
    )
    supported: bool = Field(
        ...,
        description='当前形态是否支持 WebUI 更新（部署目录存在 VERSION + bin/hq 布局；源码形态 false，前端「立即更新」置灰依据）',
    )


class UpdateProxyRequest(BaseModel):
    proxy: str = Field(
        ...,
        description='代理 URL（null=直连；自定义值须为合法 URL，非法 400 INVALID_REQUEST）',
    )


class File(BaseModel):
    id: int | None = None
    filename: str | None = None
    duplicate: bool | None = Field(
        None, description='与既有候选同名且内容哈希一致的提示（不阻断导入，另行建目）'
    )


class Queue1(BaseModel):
    queue_id: str | None = None
    name: str | None = None


class CandidateCreate(BaseModel):
    files: list[File]
    queue: Queue1 | None = Field(
        None,
        description='M2；queue_from_folder=true 且成员数 2–10 成队时返回，回落（越界拒绝成队）为 null',
    )
    queue_fallback_reason: str | None = Field(
        None,
        description='M2；越界拒绝成队回落全部候选时的回落原因（如「受支持文件 11 个，超出队列成员上限 10」），未回落为 null',
    )


class SubmitResponse(BaseModel):
    seat_id: int
    task_id: int
    normalized: bool | None = Field(
        False,
        description='M2；本次提交核验对输入副本执行了 CRLF→LF 或空行规约变更（queue 提交逐成员核验，任一成员规范化即 true）；前端据此展示「已自动规范化」注记，不自行实现规约检测',
    )
