/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["getSystemHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读全部设置（两级分组） */
        get: operations["getSettings"];
        /** 批量写运行级设置（全有或全无） */
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 分页列表（含实时 title）
         * @description items 先按导入时间倒序（created_at，新批在上）对全量排序后再分页， 同一秒导入的同批文件批内按文件名自然序（不区分大小写、字母先于数字， 与 web/src/parse/naturalsort 同规则），跨页全局有序。
         */
        get: operations["listCandidates"];
        put?: never;
        /**
         * 导入（multipart，M1 实施；M0 mock）
         * @description 支持 files[]（批量）/ 文件夹导入 mode=files|folder
         */
        post: operations["importCandidates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 候选详情 */
        get: operations["getCandidate"];
        put?: never;
        post?: never;
        /** 剔除候选（删除任务实体唯一入口） */
        delete: operations["deleteCandidate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分块预览 */
        get: operations["previewCandidate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 完整输入纯文本（提交确认框用） */
        get: operations["getCandidateInput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/blocks/{section}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 分块编辑保存（M2 实施；id 跨形态延续）
         * @description section ∈ link0/route/title/charge_mult/additional-<n>；molecule 不可编辑
         */
        put: operations["saveBlock"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 行内提交（经待执行队列；满员 409） */
        post: operations["submitCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 队列列表 */
        get: operations["listQueues"];
        put?: never;
        /** 创建队列（成员 2–10 校验，M2 实施；M0 mock） */
        post: operations["createQueue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 队列详情（含成员概览与失败记录） */
        get: operations["getQueue"];
        put?: never;
        post?: never;
        /** 删除队列（二次确认在前端） */
        delete: operations["deleteQueue"];
        options?: never;
        head?: never;
        /** 更新 {name?/member_ids?/skip_failed?}（全量有序、原子，M2 实施） */
        patch: operations["updateQueue"];
        trace?: never;
    };
    "/queues/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 直接提交（保存并进入执行，M2 实施） */
        post: operations["submitQueue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 待执行席位 + 容量 + 窗口信息 */
        get: operations["getPending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pending/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 整席重排 {seat_order:[]}（全量、原子，M1 实施） */
        put: operations["reorderPending"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pending/seats/{seat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 整席移除（单任务退候选/队列回退未提交，M1 实施） */
        delete: operations["removeSeat"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pending/seats/{seat_id}/members/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 席位内移除未执行成员（M1 实施） */
        delete: operations["removeSeatMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 在跑列表（并行同屏，按 id 键控） */
        get: operations["listExecutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 执行详情 */
        get: operations["getExecution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executions/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动停止（二次确认在前端；归因 manually_stopped，M1 实施） */
        post: operations["stopExecution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页列表 */
        get: operations["listHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 历史详情（终态冻结字段全量） */
        get: operations["getHistoryEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}/input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 输入原文（run/<id>/ 实际执行副本；skipped 回落任务副本） */
        get: operations["getHistoryInput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}/output": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 输出纯文本预览（?download 触发导出；截断容错） */
        get: operations["getHistoryOutput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 归档（唯一冻结后可变操作） */
        post: operations["archiveHistoryEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}/requeue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重新排队（原样重跑；满员 409，M1 实施） */
        post: operations["requeueHistoryEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}/return-candidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退回候选（新 id、带来源标记，M1 实施） */
        post: operations["returnCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动触发过期 chk/rwf 清理（返回清理统计，M1 实施） */
        post: operations["cleanupTransients"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE 事件流（契约见 sse.md） */
        get: operations["sseEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 任务粒度状态机（roadmap §2.1）；acrchived 是历史条目标记非任务态
         * @enum {string}
         */
        TaskState: "staged" | "running" | "succeeded" | "failed" | "skipped";
        /**
         * @description 队列四态；completed 为唯一稳定终态，失败自动回退为 unsubmitted
         * @enum {string}
         */
        QueueState: "unsubmitted" | "submitted" | "executing" | "completed";
        /**
         * @description 队列最近一次执行结束原因
         * @enum {string}
         */
        QueueFinishReason: "success" | "abort_on_failure" | "finished_with_failures" | "manually_stopped";
        /**
         * @description 候选来源标记（roadmap §2.1 退回路径穷举）
         * @enum {string}
         */
        CandidateOrigin: "imported" | "returned_unrun" | "returned_failed" | "returned_succeeded";
        /**
         * @description 历史列表排序：submitted_desc 提交时间倒序（默认，id 逆序实现）； finished_desc / finished_asc 按完成时间（finished_at，终态统一存在）； filename_asc / filename_desc 按文件名自然序（不区分大小写、字母先于 数字，与候选列表批内同规则）。各排序并列时保持提交倒序（稳定排序）， 全量排序后分页，跨页全局有序。
         * @enum {string}
         */
        HistorySort: "submitted_desc" | "finished_desc" | "finished_asc" | "filename_asc" | "filename_desc";
        /**
         * @description 执行终态归因；succeeded 为 null
         * @enum {string}
         */
        FailureCause: "manually_stopped" | "program_error" | "external_interrupt" | "predecessor_failed" | "queue_manually_stopped";
        /**
         * @description 待执行席位类型
         * @enum {string}
         */
        SeatKind: "task" | "queue";
        /**
         * @description 设置项生效语义（m0-plan §2.2）；immediate_retroactive 仅席位上限
         * @enum {string}
         */
        EffectKind: "immediate" | "immediate_retroactive" | "new_submissions" | "on_restart";
        ErrorBody: {
            error: {
                /** @description SCREAMING_SNAKE_CASE 错误码全集枚举（见文件头/m0-plan §2.1.1） */
                code: string;
                message: string;
                /** @description 错误附加信息（如越界值、逐字段错误数组） */
                details?: Record<string, never> | null;
            };
        };
        PageEnvelope: {
            /** @description 当前页数据（具体 schema 由各端点 response 覆盖） */
            items: Record<string, never>[];
            page: number;
            page_size: number;
            total: number;
        };
        /** @description 候选任务（创建即完整，此后不变；title 不落库，展示时实时解析） */
        Candidate: {
            /** @description C；与后续 Task 同 id（跨形态延续，roadmap §2.6 ③） */
            id: number;
            /** @description C；导入文件名（退回候选沿用任务文件名） */
            filename: string;
            origin: components["schemas"]["CandidateOrigin"];
            /** @description C；仅 returned_failed：归因附注；其余 null */
            failure_note: string | null;
            /**
             * Format: date-time
             * @description C；补充字段提案
             */
            created_at: string;
            /** @description —；响应中实时解析注入（解析失败为 null），不落库（roadmap §2.6 ①） */
            title?: string | null;
        };
        /** @description 任务（零自有属性，纯关系；无独立端点，作为嵌套表示） */
        Task: {
            /** @description C；同候选 id */
            id: number;
            /** @description C/T；归属队列，直接提交者为 null */
            queue_id?: string | null;
            /** @description T；队列内顺序（0 起） */
            position: number;
            /**
             * @description C/T；墙钟上限，0=不限制；M0/M1 契约占位
             * @default 0
             */
            time_limit_s: number;
            /** @description T；派生展示字段 */
            state: components["schemas"]["TaskState"];
        };
        /** @description 队列（生命周期见 roadmap §2.1） */
        Queue: {
            /** @description C；随机 6 位 base32（生成时对照全库查重） */
            id: string;
            /** @description C/T；默认 yyyymmddhhmmss 时间戳 */
            name: string;
            /** @description C/T；有序成员（创建校验 2–10；此后只减不增、≥1) */
            member_ids: number[];
            /** @description C/T；跳过失败任务开关 */
            skip_failed: boolean;
            state: components["schemas"]["QueueState"];
            /** @description T；失败回退标记 */
            rollback_flag: boolean;
            /** @description T；回退次数，0 起 */
            rollback_count: number;
            /** @description T；队列成功终态时清 null */
            last_failure: {
                finish_reason?: components["schemas"]["QueueFinishReason"];
                /** @description 失败位置（任务 id） */
                failure_positions?: number[];
                members?: {
                    task_id?: number;
                    state?: components["schemas"]["TaskState"];
                    cause?: components["schemas"]["FailureCause"];
                }[];
            } | null;
            /**
             * @description T；最近一次执行结束时写入；取值同 QueueFinishReason
             * @enum {string|null}
             */
            finish_reason: "success" | "abort_on_failure" | "finished_with_failures" | "manually_stopped" | null;
            /**
             * Format: date-time
             * @description C；补充字段提案
             */
            created_at: string;
            /**
             * Format: date-time
             * @description T；补充字段提案
             */
            updated_at?: string;
        };
        /** @description 待执行席位（get /pending 响应项） */
        PendingSeat: {
            /** @description C；席位标识（追加自增） */
            seat_id: number;
            kind: components["schemas"]["SeatKind"];
            /** @description C；kind=task 时 */
            task_id?: number | null;
            /** @description C；kind=queue 时 */
            queue_id?: string | null;
            /** @description T；席位顺序（0 起） */
            position: number;
            /** @description T；队列席位成员概览（kind=task 为单元素） */
            members: {
                task_id: number;
                filename: string;
                state: components["schemas"]["TaskState"];
            }[];
            /** @description T；并行窗口已触及 → 不可整席重排/移除 */
            locked: boolean;
        };
        /** @description GET /pending 响应（席位 + 全局容量/窗口） */
        PendingResponse: {
            seats: components["schemas"]["PendingSeat"][];
            capacity: {
                /** @description 在途席位上限（运行级设置，默认 3） */
                limit: number;
                occupied: number;
                available: number;
            };
            /** @description 当前并行执行数 */
            window_size: number;
        };
        /** @description 运行/已完成执行（运行视图；终态见 HistoryEntry） */
        Execution: {
            /** @description C；派发时创建；run/<id>/ 派生 */
            id: number;
            /** @description C */
            task_id: number;
            /** @description C */
            queue_id: string | null;
            /** @description 运行视图只出现 running（staged 由 /pending 表达） */
            state: components["schemas"]["TaskState"];
            /** @description C；冗余自任务，列表展示用 */
            filename: string;
            /**
             * Format: date-time
             * @description C
             */
            submitted_at: string;
            /**
             * Format: date-time
             * @description T；running 时补
             */
            started_at?: string | null;
            /** @description C；sha256:<hex>，skipped 无（null） */
            input_hash: string | null;
            /** @description C；Link0 声明与补齐标记（roadmap §2.6） */
            resources: {
                nproc: {
                    value: number;
                    defaulted: boolean;
                };
                mem_gb: {
                    value: number;
                    defaulted: boolean;
                };
            };
            /** @description T；提交 HQ 后回填（M0 mock 给演示值） */
            hq_job_id?: number | null;
            /** @description T；运行中实时（psutil） */
            monitor?: {
                cpu_percent?: number;
                mem_rss_mb?: number;
                elapsed_s?: number;
            } | null;
            /** @description T；增量解析注入 */
            progress?: {
                opt_step?: number | null;
                scf_cycle?: number | null;
                converged?: boolean | null;
                last_line?: string | null;
            } | null;
        };
        /** @description 历史条目（终态冻结；Execution 超集 + 终态字段） */
        HistoryEntry: components["schemas"]["Execution"] & {
            /**
             * Format: date-time
             * @description F
             */
            finished_at: string;
            /**
             * @description F；终态归因（同 FailureCause）；succeeded 为 null
             * @enum {string|null}
             */
            cause: "manually_stopped" | "program_error" | "external_interrupt" | "predecessor_failed" | "queue_manually_stopped" | null;
            /** @description F；started_at→finished_at 派生 */
            wall_time_s: number;
            /** @description F；仅 succeeded */
            monitor_summary?: {
                cpu_peak_percent?: number;
                mem_peak_mb?: number;
                stall_alerts?: number;
                stall_total_minutes?: number;
            } | null;
            /** @description F；非正常终止保全快照标记与位置 */
            chk_snapshot: {
                protected: boolean;
                /** @description 保护子目录位置；正常结束时 null */
                location: string | null;
            };
            /** @description F→；冻结后唯一可变字段 */
            archived: boolean;
            /** @description M3 占位，恒 null（Result 字段全集随 M3 契约 diff 一次性扩展） */
            result_ref: string | null;
        };
        /** @description 分子说明节统计（Hill 记法元素统计） */
        MoleculeSummary: {
            atom_count: number;
            /** @description Hill 记法，如 H2O1、C6H6O1（计数 1 显式） */
            formula: string;
            variables_present: boolean;
            constants_present: boolean;
        };
        /** @description 附加输入节（由 route 关键词触发） */
        InputBlock: {
            lines: string[];
            /** @description 该节是否需要终止空行（以手册 Section Ordering 表逐节为准） */
            terminator_blank: boolean;
        };
        /** @description 分块预览（M0 预览与 M2 编辑共用；重组空行不变式见 m0-plan §2.2） */
        InputPreview: {
            candidate_id: number;
            filename: string;
            blocks: {
                link0: {
                    lines: string[];
                    /** @description 缺失 %NProcShared/%Mem 等（驱动提交确认框琥珀警告） */
                    missing: string[];
                };
                route: string;
                title: string | null;
                charge_mult: string;
                molecule: components["schemas"]["MoleculeSummary"];
                additional_sections: components["schemas"]["InputBlock"][];
            };
            /** @description 解析失败节信息（预览尽力而为；导入端点才严格校验） */
            parse_errors?: {
                section: string;
                line: number;
                message: string;
            }[];
        };
        /** @description 设置项（元数据供前端数据驱动渲染） */
        SettingItem: {
            key: string;
            /** @description 实际值（scalar；类型由 value_type 决定） */
            value: (string | number | boolean) | null;
            /** @enum {string} */
            value_type?: "string" | "integer" | "number" | "boolean";
            range?: {
                min?: number | null;
                max?: number | null;
            } | null;
            /** @description false=启动级只读 */
            editable: boolean;
            effect: components["schemas"]["EffectKind"];
            /** @description 启动级参数的环境变量名（G16WEB_ 前缀） */
            env_var?: string | null;
            description?: string;
        };
        /** @description GET/PUT /settings 响应（两级分组） */
        SettingsResponse: {
            startup: components["schemas"]["SettingItem"][];
            runtime: components["schemas"]["SettingItem"][];
        };
        /** @description PUT /settings 请求体（全有或全无；任一项校验失败整批拒绝） */
        SettingsUpdate: {
            values: {
                [key: string]: unknown;
            };
        };
        /** @description POST /candidates 响应（导入，M1 实施；M0 mock） */
        CandidateCreate: {
            files: {
                id?: number;
                filename?: string;
                /** @description 与既有候选同名且内容哈希一致的提示（不阻断导入，另行建目） */
                duplicate?: boolean;
            }[];
        };
        SubmitResponse: {
            seat_id: number;
            task_id: number;
        };
    };
    responses: {
        /** @description 统一错误结构 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: {
        PageParam: number;
        PageSizeParam: number;
        CandidateId: number;
        QueueId: string;
        ExecutionId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSystemHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        version: string;
                        uptime_s: number;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 设置全集 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description 更新后全集 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listCandidates: {
        parameters: {
            query?: {
                origin?: components["schemas"]["CandidateOrigin"];
                page?: components["parameters"]["PageParam"];
                page_size?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分页候选列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEnvelope"] & {
                        items?: components["schemas"]["Candidate"][];
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    importCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    files: string[];
                    /**
                     * @default files
                     * @enum {string}
                     */
                    mode?: "files" | "folder";
                };
            };
        };
        responses: {
            /** @description 导入结果 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateCreate"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    getCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 候选详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已剔除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    previewCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分块结构 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InputPreview"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getCandidateInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 输入原文 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            404: components["responses"]["Error"];
        };
    };
    saveBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CandidateId"];
                section: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    lines: string[];
                };
            };
        };
        responses: {
            /** @description 更新后的完整预览结构 + 非阻断警告 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InputPreview"] & {
                        warnings?: {
                            line: number;
                            keyword: string;
                            /** @description 如 keyword_spell */
                            kind: string;
                            suggestion: string;
                        }[];
                    };
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    submitCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default 0 */
                    time_limit_s?: number;
                };
            };
        };
        responses: {
            /** @description 已入待执行队列 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResponse"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listQueues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 队列列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Queue"][];
                };
            };
        };
    };
    createQueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    member_ids: number[];
                    skip_failed: boolean;
                };
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Queue"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    getQueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["QueueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 队列详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Queue"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteQueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["QueueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    updateQueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["QueueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    member_ids?: number[];
                    skip_failed?: boolean;
                };
            };
        };
        responses: {
            /** @description 更新后队列 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Queue"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    submitQueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["QueueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已提交 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResponse"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getPending: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 待执行队列全量 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingResponse"];
                };
            };
        };
    };
    reorderPending: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    seat_order: number[];
                };
            };
        };
        responses: {
            /** @description 重排后全量 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingResponse"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    removeSeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已移除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    removeSeatMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seat_id: number;
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 移除后全量 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingResponse"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listExecutions: {
        parameters: {
            query?: {
                state?: components["schemas"]["TaskState"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 在跑执行列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Execution"][];
                };
            };
        };
    };
    getExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 执行详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Execution"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    stopExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已停止 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listHistory: {
        parameters: {
            query?: {
                state?: components["schemas"]["TaskState"];
                queue_id?: string;
                archived?: boolean;
                sort?: components["schemas"]["HistorySort"];
                page?: components["parameters"]["PageParam"];
                page_size?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分页历史列表（默认 archived=false） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEnvelope"] & {
                        items?: components["schemas"]["HistoryEntry"][];
                    };
                };
            };
        };
    };
    getHistoryEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 历史条目 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntry"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getHistoryInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 输入原文 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getHistoryOutput: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 输出文本 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            404: components["responses"]["Error"];
        };
    };
    archiveHistoryEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已归档 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    requeueHistoryEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已入待执行队列 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResponse"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    returnCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 新候选 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    cleanupTransients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 清理统计 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        checked: number;
                        removed_chk: number;
                        removed_rwf: number;
                    };
                };
            };
        };
    };
    sseEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 流 */
            200: {
                headers: {
                    "Content-Type"?: string;
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
