/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["getSystemHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 触发服务重启（异步；危险操作需前端二次确认）
         * @description 受理后 detached 拉起重启脚本（先快照当前进程 cmdline/environ/cwd 与 监听端口），服务 SIGTERM 优雅自退（不杀 HQ，§8.7：计算任务不受 WebUI 重启影响），脚本等进程退出与端口释放后按快照原命令/环境/工作 目录重新拉起并探活 /system/health；期间 SSE 断开由客户端看门狗重连。 与更新流程互斥：进行中 409 UPDATE_IN_PROGRESS（复用既有码）。 前端须二次确认且在存在运行中执行时改用长按确认（不新增错误码， 运行中执行的分级确认属前端交互语义，后端不据此拦截）。
         */
        post: operations["restartSystem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读全部设置（两级分组） */
        get: operations["getSettings"];
        /** 批量写运行级设置（全有或全无） */
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 最近检查结果与更新流程状态（页面恢复用）
         * @description 更新卡进入/刷新页面时拉取恢复，不触发重查。跨服务重启经部署目录两份伴生 文件恢复：update-state（apply 流程标记；done/failed 恢复态被本端点消费后 删除，下次成功检查兜底清理）与 .update-check（最近检查结果 latest_version/last_checked_at，常驻不清理）。
         */
        get: operations["getUpdateStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 触发一次检查（同步返回）
         * @description 探测远端 releases/latest/download/VERSION 附件（与 update.sh --check 同源， 免 GitHub API 限流），语义化版本逐段比较（剥 v 前缀，仅严格更大算有更新）。 自动检查（凌晨 1:00 锚定档期，运行级参数 update_check_interval）与本端点 共用实现，只发现不安装。
         */
        post: operations["checkUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 触发更新（异步执行；三守卫 + 同步预检）
         * @description 守卫：存在 running 执行时 409 UPDATE_BLOCKED_RUNNING（仅 running 拦截， staged 随重启对账恢复）；流程进行中 409 UPDATE_IN_PROGRESS；源码形态 409 UPDATE_UNSUPPORTED。已最新 200 幂等返回 phase=up_to_date（无更新不是 错误）。有更新先同步预检：探测远端 VERSION 失败 → 502 UPDATE_CHECK_FAILED； 拉 .sha256 验下载通道失败 → 502 UPDATE_DOWNLOAD_FAILED（预检失败均不进 异步、不动任何文件）。预检通过 202 受理，下载/校验/替换/重启转后台执行， 进度经 SSE update.progress/update.phase 推送。
         */
        post: operations["applyUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update/proxy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 设置代理通道（写工作区 .update-proxy，即时生效）
         * @description 与 update.sh 共用同一份工作区 .update-proxy 配置（URL 原文落盘且无尾 换行；启动时自动从部署目录旧位置一次性搬迁）；null=直连。自定义值非法 400 INVALID_REQUEST（既有码，不新增错误码）。
         */
        put: operations["setUpdateProxy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取前端视图偏好（列表排序规则等）
         * @description 返回已持久化的全部偏好键值（工作区 SQLite ui_prefs 表，跨重启/更新/ 断联不丢）；无记录键不在响应中，前端各自回落默认值。
         */
        get: operations["getUiPreferences"];
        /**
         * 写入前端视图偏好（合并 upsert，整批校验）
         * @description 只更新请求体中出现的键（合并语义），返回合并后全量。键白名单与值域 （queues.sort/history.sort/archive.sort）整批校验：任一未知键或越域值 整批拒绝 400 INVALID_REQUEST（既有码，不新增错误码）。不发 SSE 事件 （视图偏好为单浏览器态，不做跨标签页同步）。
         */
        put: operations["updateUiPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 分页列表（含实时 title）
         * @description items 排序：回退候选（origin=returned_*）置顶、导入候选在后，两组内 均按 created_at 倒序（最新在上），让回退条目一眼可见；同一秒导入的 批内按 id 逆序（后导入在前）。排序唯一实现在取数端，切片前全量排序， 跨页全局有序。
         */
        get: operations["listCandidates"];
        put?: never;
        /**
         * 导入（multipart，M1 实施；M0 mock）
         * @description 支持 files[]（批量）/ 文件夹导入 mode=files|folder。M2 增补导入成队： queue_from_folder=true 且 mode=folder 时，导入后以候选转换并创建队列 （name=folder_name，受支持文件数 2–10 方可成队；越界拒绝成队、回落为 全部生成候选并在 queue_fallback_reason 明示原因）。mode=files 时显式 queue_from_folder=true → 422。成队事件序列：candidates.changed(created) ×N → candidates.changed(moved_out) ×N → queues.changed(created)。
         */
        post: operations["importCandidates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 候选详情 */
        get: operations["getCandidate"];
        put?: never;
        post?: never;
        /** 剔除候选（删除任务实体唯一入口） */
        delete: operations["deleteCandidate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 分块预览
         * @description id 跨形态延续（M2）：候选与失败回退队列成员（unsubmitted 且 rollback_flag=true，与 PUT blocks 守卫一致）可读； 其余形态（新建未提交成员/已提交/在途/终态）404。
         */
        get: operations["previewCandidate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 完整输入纯文本（提交确认框用）
         * @description id 跨形态延续（M2）：候选与失败回退队列成员（守卫与 PUT blocks 一致） 可读，供分块编辑初始化与 CRLF 检出；其余形态 404。
         */
        get: operations["getCandidateInput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/blocks/{section}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 分块编辑保存（M2 实施；id 跨形态延续）
         * @description section ∈ link0/route/title/charge_mult/additional-<n>；molecule 不可编辑
         */
        put: operations["saveBlock"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 行内提交（经待执行队列；满员 409） */
        post: operations["submitCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 队列列表 */
        get: operations["listQueues"];
        put?: never;
        /** 创建队列（成员 2–10 校验，M2 实施；M0 mock） */
        post: operations["createQueue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 队列详情（含成员概览与失败记录） */
        get: operations["getQueue"];
        put?: never;
        post?: never;
        /** 删除队列（二次确认在前端） */
        delete: operations["deleteQueue"];
        options?: never;
        head?: never;
        /** 更新 {name?/member_ids?/skip_failed?}（全量有序、原子，M2 实施） */
        patch: operations["updateQueue"];
        trace?: never;
    };
    "/queues/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 直接提交（保存并进入执行，M2 实施） */
        post: operations["submitQueue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 待执行席位 + 容量 + 窗口信息 */
        get: operations["getPending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pending/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 整席重排 {seat_order:[]}（全量、原子，M1 实施） */
        put: operations["reorderPending"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pending/seats/{seat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 整席移除（单任务退候选/队列回退未提交，M1 实施） */
        delete: operations["removeSeat"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pending/seats/{seat_id}/members/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 席位内移除未执行成员（M1 实施） */
        delete: operations["removeSeatMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 在跑列表（并行同屏，按 id 键控） */
        get: operations["listExecutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 执行详情 */
        get: operations["getExecution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executions/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动停止（二次确认在前端；归因 manually_stopped，M1 实施） */
        post: operations["stopExecution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页列表 */
        get: operations["listHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 历史详情（终态冻结字段全量） */
        get: operations["getHistoryEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}/input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 输入原文（run/<id>/ 实际执行副本；skipped 回落任务副本） */
        get: operations["getHistoryInput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}/output": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 输出纯文本预览（?download 触发导出；截断容错） */
        get: operations["getHistoryOutput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 归档（唯一冻结后可变操作） */
        post: operations["archiveHistoryEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}/requeue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重新排队（原样重跑；满员 409，M1 实施） */
        post: operations["requeueHistoryEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}/return-candidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退回候选（新 id、带来源标记，M1 实施） */
        post: operations["returnCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动触发过期 chk/rwf 清理（返回清理统计，M1 实施） */
        post: operations["cleanupTransients"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 批量导出选中条目的输出文件（ZIP；逐条 .out 命名）
         * @description 按执行 id 集合打包 run/<id>/input.log（G16 输出）为 ZIP 下载：
         *     条目内命名 <任务stem>.out（正规输出扩展），同一任务多次执行产生
         *     同名冲突时全部改用「三位补零执行 id-<stem>.out」前缀区分；
         *     无输出文件的条目（skipped/输出已缺）跳过并在包内 _导出说明.txt
         *     逐条登记，选中条目全部无输出时 404。响应
         *     Content-Disposition: attachment; filename=gauforge-outputs-<时刻>.zip。
         */
        post: operations["exportHistoryOutputs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result 概览（读 analysis.json；非 succeeded 或缺失且重建失败 409，M3） */
        get: operations["getAnalysisOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}/analysis/convergence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SCF 迹线+几何收敛+能量序列（块缺失 422 ANALYSIS_PARSE_FAILED，M3） */
        get: operations["getAnalysisConvergence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}/analysis/frequencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 频率表与红外强度（无频率任务 422 ANALYSIS_PARSE_FAILED，M3） */
        get: operations["getAnalysisFrequencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}/analysis/orbitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 轨道能量清单（无 MO 表 422 ANALYSIS_PARSE_FAILED，建议 Pop=Reg/Full，M3） */
        get: operations["getAnalysisOrbitals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}/analysis/cube": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 生成 cube（幂等：同参数返回既有 cube_id；白名单/上界越界 422， 生成失败 502、cubegen 缺失 503，M3） */
        post: operations["generateCube"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/{id}/analysis/cube/{cube_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** cube 文件流（chemical/x-cube；前端 3Dmol 直接 fetch，M3） */
        get: operations["downloadCube"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/workspace-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 工作区 .out/.log 只读分析（一次性四块合一；路径守卫失败 （越界/空路径/后缀不符）400、缺失 404、不可解析/超时 422；不落库，M3） */
        post: operations["analyzeWorkspaceOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 空间占用统计与阈值告警（M3.7，只读；entries 降序截断前 50 条） */
        get: operations["getStorageUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE 事件流（契约见 sse.md） */
        get: operations["sseEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 任务粒度状态机（roadmap §2.1）；acrchived 是历史条目标记非任务态
         * @enum {string}
         */
        TaskState: "staged" | "running" | "succeeded" | "failed" | "skipped";
        /**
         * @description 队列四态；completed 为唯一稳定终态，失败自动回退为 unsubmitted
         * @enum {string}
         */
        QueueState: "unsubmitted" | "submitted" | "executing" | "completed";
        /**
         * @description 队列最近一次执行结束原因
         * @enum {string}
         */
        QueueFinishReason: "success" | "abort_on_failure" | "finished_with_failures" | "manually_stopped";
        /**
         * @description 候选来源标记（roadmap §2.1 退回路径穷举）
         * @enum {string}
         */
        CandidateOrigin: "imported" | "returned_unrun" | "returned_failed" | "returned_succeeded";
        /**
         * @description 历史列表排序：submitted_desc 提交时间倒序（默认，id 逆序实现）； finished_desc / finished_asc 按完成时间（finished_at，终态统一存在）； filename_asc / filename_desc 按文件名自然序（不区分大小写、字母先于 数字）。各排序并列时保持提交倒序（稳定排序）， 全量排序后分页，跨页全局有序。
         * @enum {string}
         */
        HistorySort: "submitted_desc" | "finished_desc" | "finished_asc" | "filename_asc" | "filename_desc";
        /**
         * @description 队列页排序：default 默认序（回退置顶、组内创建时间倒序）； name_asc / name_desc 队列名称 zh-Hans-CN 字典序升/降序。
         * @enum {string}
         */
        QueueSortKey: "default" | "name_asc" | "name_desc";
        /** @description 前端视图偏好（工作区 SQLite ui_prefs 表；键白名单与值域见 UiPreferencesUpdate） */
        UiPreferences: {
            /** @description 偏好键值（仅含已持久化键；值为所选排序枚举串） */
            prefs: {
                [key: string]: string;
            };
        };
        /** @description PUT /ui-preferences 请求体（合并 upsert：只更新出现的键） */
        UiPreferencesUpdate: {
            /** @description 键白名单与值域：queues.sort ∈ QueueSortKey；history.sort 与 archive.sort ∈ HistorySort（归档页与历史页同组件、键分立各自记忆）。 未知键或越域值整批 400 INVALID_REQUEST。 */
            prefs: {
                [key: string]: string;
            };
        };
        /**
         * @description 执行终态归因；succeeded 为 null
         * @enum {string}
         */
        FailureCause: "manually_stopped" | "program_error" | "external_interrupt" | "predecessor_failed" | "queue_manually_stopped";
        /**
         * @description 待执行席位类型
         * @enum {string}
         */
        SeatKind: "task" | "queue";
        /**
         * @description 设置项生效语义（m0-plan §2.2）；immediate_retroactive 仅席位上限
         * @enum {string}
         */
        EffectKind: "immediate" | "immediate_retroactive" | "new_submissions" | "on_restart";
        ErrorBody: {
            error: {
                /** @description SCREAMING_SNAKE_CASE 错误码全集枚举（SSOT 载体见本文件头「错误码全集」清单，24 码 + 两张 reason 词表） */
                code: string;
                message: string;
                /** @description 错误附加信息（如越界值、逐字段错误数组） */
                details?: Record<string, never> | null;
            };
        };
        PageEnvelope: {
            /** @description 当前页数据（具体 schema 由各端点 response 覆盖） */
            items: Record<string, never>[];
            page: number;
            page_size: number;
            total: number;
        };
        /** @description 候选任务（创建即完整，此后不变；title 不落库，展示时实时解析） */
        Candidate: {
            /** @description C；与后续 Task 同 id（跨形态延续，roadmap §2.6 ③） */
            id: number;
            /** @description C；导入文件名（退回候选沿用任务文件名） */
            filename: string;
            origin: components["schemas"]["CandidateOrigin"];
            /** @description C；仅 returned_failed：归因附注；其余 null */
            failure_note: string | null;
            /**
             * Format: date-time
             * @description C；补充字段提案
             */
            created_at: string;
            /** @description —；响应中实时解析注入（解析失败为 null），不落库（roadmap §2.6 ①） */
            title?: string | null;
        };
        /** @description 任务（零自有属性，纯关系；无独立端点，作为嵌套表示） */
        Task: {
            /** @description C；同候选 id */
            id: number;
            /** @description C/T；归属队列，直接提交者为 null */
            queue_id?: string | null;
            /** @description T；队列内顺序（0 起） */
            position: number;
            /**
             * @description C/T；墙钟上限，0=不限制；M0/M1 契约占位
             * @default 0
             */
            time_limit_s: number;
            /** @description T；派生展示字段 */
            state: components["schemas"]["TaskState"];
        };
        /** @description 队列（生命周期见 roadmap §2.1） */
        Queue: {
            /** @description C；随机 6 位 base32（生成时对照全库查重） */
            id: string;
            /** @description C/T；默认 yyyymmddhhmmss 时间戳 */
            name: string;
            /** @description C/T；有序成员（创建校验 2–10；此后只减不增、≥1) */
            member_ids: number[];
            /** @description C/T；跳过失败任务开关 */
            skip_failed: boolean;
            state: components["schemas"]["QueueState"];
            /** @description T；失败回退标记 */
            rollback_flag: boolean;
            /** @description T；回退次数，0 起 */
            rollback_count: number;
            /** @description T；队列成功终态时清 null */
            last_failure: {
                finish_reason?: components["schemas"]["QueueFinishReason"];
                /** @description 失败位置（任务 id） */
                failure_positions?: number[];
                members?: {
                    task_id?: number;
                    state?: components["schemas"]["TaskState"];
                    cause?: components["schemas"]["FailureCause"];
                }[];
            } | null;
            /**
             * @description T；最近一次执行结束时写入；取值同 QueueFinishReason
             * @enum {string|null}
             */
            finish_reason: "success" | "abort_on_failure" | "finished_with_failures" | "manually_stopped" | null;
            /**
             * Format: date-time
             * @description C；补充字段提案
             */
            created_at: string;
            /**
             * Format: date-time
             * @description T；补充字段提案
             */
            updated_at?: string;
        };
        /** @description C；Link0 声明与补齐标记（roadmap §2.6）；defaulted=true 表示运行级缺省值补齐 */
        Resources: {
            nproc: {
                value: number;
                defaulted: boolean;
            };
            mem_gb: {
                value: number;
                defaulted: boolean;
            };
        };
        /** @description 待执行席位（get /pending 响应项） */
        PendingSeat: {
            /** @description C；席位标识（追加自增） */
            seat_id: number;
            kind: components["schemas"]["SeatKind"];
            /** @description C；kind=task 时 */
            task_id?: number | null;
            /** @description C；kind=queue 时 */
            queue_id?: string | null;
            /** @description C；kind=queue 时的队列名（实时取自队列） */
            queue_name?: string | null;
            /**
             * Format: date-time
             * @description T；入席时刻即提交时刻（席位 created_at）
             */
            submitted_at: string;
            /** @description T；席位顺序（0 起） */
            position: number;
            /** @description T；队列席位成员概览（kind=task 为单元素）；title/resources 实时解析，输入文件不可读时 resources 键缺省 */
            members: {
                task_id: number;
                filename: string;
                state: components["schemas"]["TaskState"];
                /** @description T；队列内序号（0 起）；kind=task 席位为 null */
                position?: number | null;
                /** @description —；响应中实时解析注入（解析失败为 null），不落库（同候选 title 口径） */
                title?: string | null;
                resources?: components["schemas"]["Resources"];
            }[];
            /** @description T；并行窗口已触及 → 不可整席重排/移除 */
            locked: boolean;
        };
        /** @description GET /pending 响应（席位 + 全局容量/窗口） */
        PendingResponse: {
            seats: components["schemas"]["PendingSeat"][];
            capacity: {
                /** @description 在途席位上限（运行级设置，默认 3） */
                limit: number;
                occupied: number;
                available: number;
            };
            /** @description 当前并行执行数 */
            window_size: number;
        };
        /** @description 运行/已完成执行（运行视图；终态见 HistoryEntry） */
        Execution: {
            /** @description C；派发时创建；run/<id>/ 派生 */
            id: number;
            /** @description C */
            task_id: number;
            /** @description C */
            queue_id: string | null;
            /** @description 运行视图只出现 running（staged 由 /pending 表达） */
            state: components["schemas"]["TaskState"];
            /** @description C；冗余自任务，列表展示用 */
            filename: string;
            /**
             * Format: date-time
             * @description C
             */
            submitted_at: string;
            /**
             * Format: date-time
             * @description T；running 时补
             */
            started_at?: string | null;
            /** @description C；sha256:<hex>，skipped 无（null） */
            input_hash: string | null;
            resources: components["schemas"]["Resources"];
            /** @description T；提交 HQ 后回填（M0 mock 给演示值） */
            hq_job_id?: number | null;
            /** @description T；运行中实时（psutil） */
            monitor?: {
                cpu_percent?: number;
                mem_rss_mb?: number;
                elapsed_s?: number;
            } | null;
            /** @description T；增量解析注入 */
            progress?: {
                opt_step?: number | null;
                scf_cycle?: number | null;
                /** @description T；第几次 SCF（Cycle 1 行出现即新一轮，自 1 递增） */
                scf_round?: number | null;
                converged?: boolean | null;
                last_line?: string | null;
            } | null;
        };
        /** @description 历史条目（终态冻结；Execution 超集 + 终态字段） */
        HistoryEntry: components["schemas"]["Execution"] & {
            /**
             * Format: date-time
             * @description F
             */
            finished_at: string;
            /**
             * @description F；终态归因（同 FailureCause）；succeeded 为 null
             * @enum {string|null}
             */
            cause: "manually_stopped" | "program_error" | "external_interrupt" | "predecessor_failed" | "queue_manually_stopped" | null;
            /** @description F；started_at→finished_at 派生 */
            wall_time_s: number;
            /** @description F；仅 succeeded */
            monitor_summary?: {
                cpu_peak_percent?: number;
                mem_peak_mb?: number;
                stall_alerts?: number;
                stall_total_minutes?: number;
            } | null;
            /** @description F；非正常终止保全快照标记与位置 */
            chk_snapshot: {
                protected: boolean;
                /** @description 保护子目录位置；正常结束时 null */
                location: string | null;
            };
            /** @description F→；冻结后唯一可变字段 */
            archived: boolean;
            /** @description M3 起：succeeded 且 run/<id>/analysis.json 落盘成功（含 degraded 降级产物）时 = "analysis.json"（执行目录内相对引用，读取方 按 run/<执行id>/ 拼接）；落盘失败/缺失恒 null。非 succeeded 恒 null （口径 m3-plan §2.1，2026-09-30 三轮审查统一） */
            result_ref: string | null;
        };
        /** @description 批量导出请求（执行 id 集合；服务端去重保序） */
        HistoryExportRequest: {
            /** @description 历史条目（终态执行）id 集合 */
            ids: number[];
        };
        /** @description 分析结果概览（仅 succeeded 执行；run/<id>/analysis.json 的契约 形状，cclib 白名单解析产物。字段集一次定死，roadmap §2.6 规则 1/3） */
        Result: {
            /**
             * @description degraded=至少一个请求块解析失败/缺失
             * @enum {string}
             */
            state: "parsed" | "degraded";
            parser: {
                name: string;
                version: string;
            };
            /** @description cclib metadata（package/package_version）；不可得时 null */
            package: {
                name: string;
                version: string;
            } | null;
            /** @description metadata.methods 摘要（如 b3lyp/6-31g(d)） */
            method: string | null;
            summary: {
                natom: number;
                nmo: number;
                nbasis: number;
                /** @description scfenergies 末值 */
                scf_energy_eV: number | null;
                /** @description eV→hartree 换算单点（供能量表直接使用） */
                scf_energy_hartree: number | null;
                /** @description optdone；非优化任务 null */
                opt_converged: boolean | null;
                /** @description vibfreqs 长度；非频率任务 null */
                freq_count: number | null;
                imaginary_freq_count: number | null;
                /** @description HOMO 序号（开壳层 α/β 两值） */
                homos: number[];
            };
            blocks: components["schemas"]["ResultBlocks"];
            /** @description degraded 时的缺失属性清单 */
            missing: string[];
            /** @description 解析异常摘要（degraded 主因） */
            parse_error: string | null;
        };
        /** @description 可用分析块清单（驱动端点可见性与前端 tab 置灰；独立组件命名， 避免与输入预览域 blocks 生成类名撞名） */
        ResultBlocks: {
            convergence: boolean;
            frequencies: boolean;
            orbitals: boolean;
            thermochemistry: boolean;
        };
        /** @description 收敛数据（GET /history/{id}/analysis/convergence；单端点响应 ≤2MB，超出按步均匀抽稀并置 downsampled=true） */
        ConvergenceResponse: {
            downsampled: boolean;
            /** @description 每几何步内各次 SCF 迭代的收敛判据列（cclib scfvalues 逐列展开） */
            scf_trace: {
                geometry_step: number;
                /** @description 每次迭代一行的判据值（列序同 scf_targets；个别判据 在迭代早期未更新时为 null——cclib scfvalues 实测含 NaN， 真机链路实证后随契约 diff 补 nullable，前端绘图按断点处理） */
                cycles: (number | null)[][];
            }[];
            /** @description SCF 判据阈值（与 cycles 列同序） */
            scf_targets: number[];
            /** @description 几何收敛判据逐几何步（优化任务；无则空数组） */
            geo_trace: {
                geometry_step: number;
                values: number[];
            }[];
            geo_targets: number[];
            /** @description 各几何步末次 SCF 能量（scfenergies；hartree/eV 双单位） */
            energy_series: components["schemas"]["EnergyPoint"][];
        };
        /** @description 能量序列单点（各几何步末次 SCF 能量，hartree/eV 双单位） */
        EnergyPoint: {
            geometry_step: number;
            energy_eV: number;
            energy_hartree: number;
        };
        /** @description 频率表与红外强度（vibfreqs/vibirs/vibsyms/vibrmasses） */
        FrequenciesResponse: {
            frequencies: {
                index: number;
                /** @description vibfreqs（1/cm） */
                frequency_cm: number;
                /** @description vibirs（km/mol） */
                ir_intensity: number | null;
                /** @description vibsyms；缺失时 null */
                symmetry: string | null;
                /** @description vibrmasses */
                reduced_mass: number | null;
                /** @description 频率 < 0（虚频标红） */
                imaginary: boolean;
            }[];
        };
        /** @description 轨道能量清单（不含 mocoeffs——系数不进响应，等值面走 cube 端点； 输出无 MO 表时 blocks.orbitals=false，提示建议 Pop=Reg/Full）。开壳层 任务 α/β 两组自旋各承载一份清单（spin 区分，各自 1..n 编号；B1 探针 实证 phenoxyls 双自旋后随契约 diff 补录） */
        OrbitalsResponse: {
            /** @description α 组轨道数（cubegen MO=<n> 上界校验基） */
            nmo: number;
            nbasis: number;
            /** @description HOMO 序号（闭壳层单值，开壳层 [α,β] 两值） */
            homos: number[];
            orbitals: {
                /** @description 同自旋组内 1 起（与 cubegen MO=<n> 同基；cube 生成 仅对 α 组，1≤n≤nmo） */
                index: number;
                energy_eV: number;
                /** @description mosyms；缺失时 null（老版输出实测全缺） */
                symmetry: string | null;
                /** @description 自旋组标记 alpha/beta；闭壳层 null（单组清单） */
                spin: string | null;
            }[];
        };
        /** @description 工作区 .out/.log 只读分析一次性负载（四块合一，与分块端点同形 嵌套；不落库、不写 result_ref；解析超时 60s 按 422 ANALYSIS_PARSE_FAILED） */
        WorkspaceOutAnalysis: {
            overview: components["schemas"]["Result"];
            convergence: components["schemas"]["ConvergenceResponse"];
            frequencies: components["schemas"]["FrequenciesResponse"];
            orbitals: components["schemas"]["OrbitalsResponse"];
        };
        /** @description cube 生成请求（kind 为类别名、服务端合成 cubegen 实参—— MO=<orbital> 与 <kind>=SCF；幂等：同参数命中已生成文件直接返回） */
        CubeRequest: {
            /**
             * @description 白名单外 422；MO 时 orbital 必填
             * @enum {string}
             */
            kind: "MO" | "Potential" | "Density" | "Spin";
            /** @description kind=MO 必填且 1≤orbital≤nmo（越界 422） */
            orbital?: number | null;
            /** @description 40–120 整数（默认 80；越界 422） */
            npts?: number | null;
        };
        /** @description 空间占用统计（M3.7，只读；entries 按总占用降序、默认截断前 50 条；纯拉取式无定时器，超阈仅警告不自动清理） */
        StorageUsage: {
            /** @description 工作区根（G16WEB_HOME）整树 apparent size——run/ 产物树、 数据库及 hq 状态、inputs 等全部内容计入（与 du -sb <工作区根> 同 口径，并发落盘下允许条目竞态容差）；运行中执行目录与无历史行的 孤儿目录一并计入；per-execution 明细仍按 run/<id> 分桶，桶外内容 仅计入总量 */
            total_bytes: number;
            /** @description disk_usage_warn_gb 换算字节数；0=禁用告警 */
            threshold_bytes: number;
            /** @description threshold_bytes>0 且 total_bytes≥threshold_bytes */
            over: boolean;
            /** @description per-execution 占用明细（含运行中条目，reclaimable 恒 0； 无历史行的孤儿目录仅计入 total_bytes、不产生明细） */
            entries: {
                execution_id: number;
                task_id: number;
                filename: string;
                total_bytes: number;
                /** @description 可被手动清理入口移除的量（与 M1 清理边界判定同源单一实现；保全快照计 0） */
                reclaimable_bytes: number;
            }[];
            /** @description 明细总数（截断前） */
            total_entries: number;
            truncated: boolean;
        };
        /** @description 分子说明节统计（Hill 记法元素统计） */
        MoleculeSummary: {
            atom_count: number;
            /** @description Hill 记法，如 H2O1、C6H6O1（计数 1 显式） */
            formula: string;
            variables_present: boolean;
            constants_present: boolean;
        };
        /** @description 附加输入节（由 route 关键词触发） */
        InputBlock: {
            lines: string[];
            /** @description 该节是否需要终止空行（以手册 Section Ordering 表逐节为准） */
            terminator_blank: boolean;
        };
        /** @description 分块预览（M0 预览与 M2 编辑共用；重组空行不变式见 m0-plan §2.2） */
        InputPreview: {
            candidate_id: number;
            filename: string;
            blocks: {
                link0: {
                    lines: string[];
                    /** @description 缺失 %NProcShared/%Mem 等（驱动提交确认框琥珀警告） */
                    missing: string[];
                };
                route: string;
                title: string | null;
                charge_mult: string;
                molecule: components["schemas"]["MoleculeSummary"];
                additional_sections: components["schemas"]["InputBlock"][];
            };
            /** @description 解析失败节信息（预览尽力而为；导入端点才严格校验） */
            parse_errors?: {
                section: string;
                line: number;
                message: string;
            }[];
        };
        /** @description 设置项（元数据供前端数据驱动渲染） */
        SettingItem: {
            key: string;
            /** @description 实际值（scalar；类型由 value_type 决定） */
            value: (string | number | boolean) | null;
            /** @enum {string} */
            value_type?: "string" | "integer" | "number" | "boolean";
            range?: {
                min?: number | null;
                max?: number | null;
                /** @description 枚举值域（string 型参数载体，如 update_check_interval 的 daily/weekly/monthly/never 四档）；非枚举参数缺省。校验不命中归 type 类错误（不扩 reason 词表） */
                enum?: string[] | null;
            } | null;
            /** @description false=启动级只读 */
            editable: boolean;
            effect: components["schemas"]["EffectKind"];
            /** @description 启动级参数的环境变量名（G16WEB_ 前缀） */
            env_var?: string | null;
            description?: string;
        };
        /** @description GET/PUT /settings 响应（两级分组）。运行级参数含自动检查更新周期 update_check_interval（string 四值枚举 daily/weekly/monthly/never，默认 weekly，经 SettingItem.range.enum 表达，v2.1.0 起；凌晨 1:00 锚定、只发现不安装） 与空间占用告警阈值 disk_usage_warn_gb（integer GB，0=禁用告警，默认 50 ——A1 决策点 5 定稿；只读告警不涉执行语义、保存即生效，M3 波 A1 起——超阈仅 警告不自动清理，m3-plan §2.6） */
        SettingsResponse: {
            startup: components["schemas"]["SettingItem"][];
            runtime: components["schemas"]["SettingItem"][];
        };
        /** @description PUT /settings 请求体（全有或全无；任一项校验失败整批拒绝） */
        SettingsUpdate: {
            values: {
                [key: string]: unknown;
            };
        };
        /**
         * @description 更新流程九相（与设置页更新卡显示状态机一一对应；available 即「发现新版本」）
         * @enum {string}
         */
        UpdatePhase: "idle" | "checking" | "available" | "up_to_date" | "downloading" | "installing" | "restarting" | "done" | "failed";
        /** @description 更新域状态对象（GET /update/status 与 check/apply/proxy 响应共用） */
        UpdateStatus: {
            /** @description 当前版本（带 v 前缀形态，如 v2.1.0；与 /system/health version 同源） */
            current_version: string;
            /** @description 最近一次检查发现的远端版本（带 v 前缀）；从未检查成功过为 null */
            latest_version?: string | null;
            /**
             * Format: date-time
             * @description 最近一次检查结束时刻（含失败；跨服务重启经部署目录 .update-check 恢复）
             */
            last_checked_at?: string | null;
            phase: components["schemas"]["UpdatePhase"];
            /** @description 供前端逐字展示的当前状态/异常文案（§3.2/§3.5 文案表，全角标点） */
            message?: string | null;
            /** @description 代理通道（读自工作区 .update-proxy，与 update.sh 共用配置；null=直连；默认代理为 URL 串 https://v4.gh-proxy.org） */
            proxy: string | null;
            /** @description 当前形态是否支持 WebUI 更新（部署目录存在 VERSION + bin/hq 布局；源码形态 false，前端「立即更新」置灰依据） */
            supported: boolean;
        };
        /** @description PUT /update/proxy 请求体 */
        UpdateProxyRequest: {
            /** @description 代理 URL（null=直连；自定义值须为合法 URL，非法 400 INVALID_REQUEST） */
            proxy: string | null;
        };
        /** @description POST /candidates 响应（导入，M1 实施；M0 mock）。M2 起含导入成队结果字段（queue_from_folder 时返回，见 POST /candidates） */
        CandidateCreate: {
            files: {
                id?: number;
                filename?: string;
                /** @description 与既有候选同名且内容哈希一致的提示（不阻断导入，另行建目） */
                duplicate?: boolean;
            }[];
            /** @description M2；queue_from_folder=true 且成员数 2–10 成队时返回，回落（越界拒绝成队）为 null */
            queue?: {
                queue_id?: string;
                name?: string;
            } | null;
            /** @description M2；越界拒绝成队回落全部候选时的回落原因（如「受支持文件 11 个，超出队列成员上限 10」），未回落为 null */
            queue_fallback_reason?: string | null;
        };
        /** @description 提交响应（行内提交/队列提交/历史重新排队三端点共用）。M2 起提交前输入核验对输入副本执行换行规范化或空行规约时置 normalized=true */
        SubmitResponse: {
            seat_id: number;
            task_id: number;
            /**
             * @description M2；本次提交核验对输入副本执行了 CRLF→LF 或空行规约变更（queue 提交逐成员核验，任一成员规范化即 true）；前端据此展示「已自动规范化」注记，不自行实现规约检测
             * @default false
             */
            normalized: boolean;
        };
    };
    responses: {
        /** @description 统一错误结构 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: {
        PageParam: number;
        PageSizeParam: number;
        CandidateId: number;
        QueueId: string;
        ExecutionId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSystemHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        version: string;
                        uptime_s: number;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    restartSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已受理（服务即将优雅重启） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "restarting";
                        message: string;
                    };
                };
            };
            /** @description 守卫拒绝（UPDATE_IN_PROGRESS） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 设置全集 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description 更新后全集 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getUpdateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 状态对象 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateStatus"];
                };
            };
        };
    };
    checkUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 检查结果状态对象 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateStatus"];
                };
            };
            /** @description 探测失败（连接超时/无法连接/远端返回异常，UPDATE_CHECK_FAILED） */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    applyUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已最新（幂等，phase=up_to_date） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateStatus"];
                };
            };
            /** @description 已受理（更新流程后台执行） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateStatus"];
                };
            };
            /** @description 守卫拒绝（UPDATE_BLOCKED_RUNNING / UPDATE_IN_PROGRESS / UPDATE_UNSUPPORTED） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 同步预检失败（UPDATE_CHECK_FAILED / UPDATE_DOWNLOAD_FAILED） */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    setUpdateProxy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProxyRequest"];
            };
        };
        responses: {
            /** @description 设置后状态对象 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateStatus"];
                };
            };
            /** @description 自定义代理 URL 非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getUiPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 偏好键值全量 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UiPreferences"];
                };
            };
        };
    };
    updateUiPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UiPreferencesUpdate"];
            };
        };
        responses: {
            /** @description 合并后偏好键值全量 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UiPreferences"];
                };
            };
            /** @description 未知键或值越域（details.errors 逐项 key/reason） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    listCandidates: {
        parameters: {
            query?: {
                origin?: components["schemas"]["CandidateOrigin"];
                page?: components["parameters"]["PageParam"];
                page_size?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分页候选列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEnvelope"] & {
                        items?: components["schemas"]["Candidate"][];
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    importCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    files: string[];
                    /**
                     * @default files
                     * @enum {string}
                     */
                    mode?: "files" | "folder";
                    /**
                     * @description M2；导入后以文件夹名为队列名保存为队列（仅 mode=folder 有效）
                     * @default false
                     */
                    queue_from_folder?: boolean;
                    /** @description M2；队列名来源（queue_from_folder=true 时必填——浏览器 webkitdirectory 上传仅携文件基名，相对路径由前端另送） */
                    folder_name?: string;
                };
            };
        };
        responses: {
            /** @description 导入结果 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateCreate"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    getCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 候选详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已剔除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    previewCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分块结构 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InputPreview"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getCandidateInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 输入原文 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            404: components["responses"]["Error"];
        };
    };
    saveBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CandidateId"];
                section: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    lines: string[];
                };
            };
        };
        responses: {
            /** @description 更新后的完整预览结构 + 非阻断警告 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InputPreview"] & {
                        warnings?: {
                            line: number;
                            keyword: string;
                            /** @description 如 keyword_spell */
                            kind: string;
                            suggestion: string;
                        }[];
                    };
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    submitCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default 0 */
                    time_limit_s?: number;
                };
            };
        };
        responses: {
            /** @description 已入待执行队列 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResponse"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listQueues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 队列列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Queue"][];
                };
            };
        };
    };
    createQueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    member_ids: number[];
                    skip_failed: boolean;
                };
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Queue"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    getQueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["QueueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 队列详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Queue"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteQueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["QueueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    updateQueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["QueueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    member_ids?: number[];
                    skip_failed?: boolean;
                };
            };
        };
        responses: {
            /** @description 更新后队列 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Queue"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    submitQueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["QueueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已提交 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResponse"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getPending: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 待执行队列全量 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingResponse"];
                };
            };
        };
    };
    reorderPending: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    seat_order: number[];
                };
            };
        };
        responses: {
            /** @description 重排后全量 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingResponse"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    removeSeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已移除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    removeSeatMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seat_id: number;
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 移除后全量 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingResponse"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listExecutions: {
        parameters: {
            query?: {
                state?: components["schemas"]["TaskState"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 在跑执行列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Execution"][];
                };
            };
        };
    };
    getExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 执行详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Execution"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    stopExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已停止 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listHistory: {
        parameters: {
            query?: {
                state?: components["schemas"]["TaskState"];
                queue_id?: string;
                archived?: boolean;
                sort?: components["schemas"]["HistorySort"];
                page?: components["parameters"]["PageParam"];
                page_size?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分页历史列表（默认 archived=false） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEnvelope"] & {
                        items?: components["schemas"]["HistoryEntry"][];
                    };
                };
            };
        };
    };
    getHistoryEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 历史条目 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntry"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getHistoryInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 输入原文 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getHistoryOutput: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 输出文本 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            404: components["responses"]["Error"];
        };
    };
    archiveHistoryEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已归档 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    requeueHistoryEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已入待执行队列 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResponse"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    returnCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 新候选 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    cleanupTransients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 清理统计 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        checked: number;
                        removed_chk: number;
                        removed_rwf: number;
                    };
                };
            };
        };
    };
    exportHistoryOutputs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryExportRequest"];
            };
        };
        responses: {
            /** @description 输出文件 ZIP 包 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getAnalysisOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result 全集（含 degraded） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getAnalysisConvergence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 收敛数据（hartree/eV 双单位） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvergenceResponse"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getAnalysisFrequencies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 频率表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrequenciesResponse"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getAnalysisOrbitals: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 轨道清单（不含系数） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrbitalsResponse"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    generateCube: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CubeRequest"];
            };
        };
        responses: {
            /** @description cube 标识 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description 参数摘要哈希；产物落 run/<id>/cubes/<cube_id>.cube */
                        cube_id: string;
                    };
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
            502: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    downloadCube: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExecutionId"];
                cube_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description cube 文件流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "chemical/x-cube": string;
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    analyzeWorkspaceOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 工作区内相对路径（后缀 ∈ {.out,.log}） */
                    path: string;
                };
            };
        };
        responses: {
            /** @description 四块合一负载 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOutAnalysis"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getStorageUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 占用统计 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageUsage"];
                };
            };
        };
    };
    sseEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 流 */
            200: {
                headers: {
                    "Content-Type"?: string;
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
